

server:
  port: 8000
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - name: "CustomGlobalFilter"
          args:
            Logging: true
        - name: CacheFilter
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

      routes:
        - id: auth-service
          uri: "lb://AUTH-SERVICE"
          predicates:
            - Path=/api/v1/auth/**
        - id: ceo-service
          uri: "lb://CEO-SERVICE"
          predicates:
            - Path=/api/v1/owner/**
          filters:
            - name: "TokenFilter"
              args:
                logging: false
        - id: store-service
          uri: "lb://STORE-SERVICE"
          predicates:
            - Path=/api/v1/store/**
        - id: menu-service
          uri: "http://localhost:9002"
          predicates:
            - Path=/api/v1/menu/**

management:
  endpoint:
    web:
      exposure:
        include: health,beans,refresh

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
