server:
  port: 9001

spring:
  application:
    name: ceo-service
  datasource:

    url: jdbc:mysql://localhost:3306/ceo?serverTimezone=Asia/Seoul
    username: root
    password: "[dhqclwoa12]"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  secret: asdfdasfsdfajdflajsjflksjdsdjlfajdfjladjflaldijflajdljflj


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true