server:
  port: 9000

spring:
  datasource:

    url: jdbc:mysql://localhost:3306/ceo?serverTimezone=Asia/Seoul
    username: root
    password: "[dhqclwoa12]"
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  secret: asdfdasfsdfajdflajsjflksjdsdjlfajdfjladjflaldijflajdljflj

